from __future__ import annotations

from typing import Any

from .paths import resolve_default_workspace_dir, resolve_sessions_dir, resolve_vector_db_path


def build_defaults() -> dict[str, Any]:
    return {
        "DINGTALK_ENABLED": False,
        "DINGTALK_CLIENT_ID": "",
        "DINGTALK_CLIENT_SECRET": "",
        "DINGTALK_ALLOW_FROM": [],
        "NAPCAT_ENABLED": True,
        "NAPCAT_WS_URL": "ws://127.0.0.1:3001",
        "NAPCAT_ACCESS_TOKEN": "",
        "NAPCAT_ALLOW_FROM": [],
        "NAPCAT_ALLOW_GROUPS": [],
        "STT_ENABLED": True,
        "STT_DEFAULT_LANGUAGE": "zh-CN",
        "STT_TIMEOUT_MS": 15000,
        "STT_MAX_CONCURRENCY": 4,
        "STT_RETRY_COUNT": 1,
        "STT_FAILOVER_ENABLED": True,
        "STT_CACHE_ENABLED": True,
        "STT_CACHE_TTL_S": 600,
        "STT_PROVIDERS": [
            {
                "id": "openai",
                "enabled": True,
                "priority": 100,
                "model": "gpt-4o-mini-transcribe",
                "apiBase": "",
                "apiKey": "",
                "formats": ["wav", "mp3", "ogg", "m4a", "flac"],
                "timeoutMs": 15000,
            },
            {
                "id": "whisper-cli",
                "enabled": True,
                "priority": 10,
                "command": "whisper",
                "argsTemplate": ["{{input}}", "--language", "{{language}}"],
                "timeoutMs": 20000,
            },
            {
                "id": "funasr-local",
                "enabled": False,
                "priority": 1,
                "model": "paraformer-zh",
                "timeoutMs": 20000,
            },
        ],
        "LLM_MODEL": "gpt-4o-mini",
        "LLM_API_KEY": "",
        "LLM_API_BASE": None,
        "LLM_EXTRA_HEADERS": {},
        "LLM_MAX_TOKENS": 8192,
        "LLM_TEMPERATURE": 0.7,
        "LLM_MAX_TOOL_ITERATIONS": 20,
        "RUNTIME_EXECUTION": {
            "maxTurns": 64,
            "maxToolCallsTotal": 256,
            "maxToolCallsPerTurn": 16,
            "maxWallTimeMs": 900000,
            "maxRecoveryAttempts": 12,
            "toolConcurrency": 8,
            "toolTimeoutMs": 60000,
            "toolFailurePolicy": "best_effort",
        },
        "RUNTIME_LOOP_GUARD": {
            "mode": "balanced",
            "fingerprintWindow": 3,
            "repeatBlockThreshold": 3,
            "onRepeat": "warn_inject",
            "slowdownBackoffMs": 500,
        },
        "LLM_MEMORY_WINDOW": 50,
        "LLM_THINKING_BUDGET_TOKENS": 0,
        "AGENTS_DEFAULTS": {},
        "AGENTS_LIST": [],
        "WORKSPACE_PATH": "workspace",
        "SESSIONS_DIR": str(resolve_sessions_dir()),
        "BRAVE_API_KEY": "",
        "EXEC_TIMEOUT": 60,
        "RESTRICT_TO_WORKSPACE": False,
        "MCP": {
            "enabled": True,
            "reloadPolicy": "diff",
            "defaultTimeoutMs": 20000,
            "servers": {},
        },
        "PLUGINS_AUTO_DISCOVERY_ENABLED": True,
        "PLUGINS_ENABLED": True,
        "PLUGINS_LOAD_PATHS": [],
        "PLUGINS_ALLOW": [],
        "PLUGINS_DENY": [],
        "PLUGINS_ENTRIES": {},
        "SKILLS_ENABLED": True,
        "SKILLS_ENTRIES": {},
        "SKILLS_LOAD_EXTRA_DIRS": [],
        "SKILLS_INSTALL_NODE_MANAGER": "npm",
        "SKILLS_INSTALL_PREFER_BREW": True,
        "SKILLS_INSTALL_TIMEOUT_MS": 300000,
        "SKILLS_SECURITY_ALLOWED_DOWNLOAD_DOMAINS": [],
        "SKILLS_LIMIT_MAX_IN_PROMPT": 150,
        "SKILLS_LIMIT_MAX_PROMPT_CHARS": 30000,
        "SKILLS_LIMIT_MAX_FILE_BYTES": 256000,
        "GLOBAL_DENY_TOOLS": [],
        "SESSION_TOOL_POLICY": {},
        "USE_UNIFIED_TOOL_ASSEMBLER": True,
        "RUNTIME_HOT_APPLY_ENABLED": True,
        "MEDIA_UNDERSTANDING": {
            "enabled": True,
            "concurrency": 2,
            "modelCapabilities": {},
            "image": {
                "enabled": True,
                "mode": "native_first",
                "defaultModel": "huoshan/doubao-seed-2-0",
                "prompt": "You are an image understanding assistant. Extract key subjects, visible text, and concise conclusions relevant to the user question.",
                "maxChars": 800,
                "models": [],
            },
            "audio": {
                "enabled": True,
                "mode": "tool_first",
                "language": "zh-CN",
                "providerProfile": "",
            },
            "video": {
                "enabled": True,
                "mode": "tool_first",
            },
            "file": {
                "enabled": True,
            },
        },
        "CHANNEL_USERS": {},
        "NOTIFY_CHANNEL": "",
        "CONTEXT_ENGINE": "vector",
        "EMBEDDING_MODEL": "text-embedding-3-small",
        "EMBEDDING_API_KEY": "",
        "EMBEDDING_API_BASE": None,
        "VECTOR_DB_PATH": str(resolve_vector_db_path()),
        "MEMORY_SEARCH_LIMIT": 8,
        "MEMORY_VECTOR_WEIGHT": 0.7,
        "MEMORY_TEXT_WEIGHT": 0.3,
        "MEMORY_MMR_LAMBDA": 0.7,
        "MEMORY_TEMPORAL_HALF_LIFE_DAYS": 30.0,
        "MEMORY_INCLUDE_SESSIONS": False,
        "MEMORY_SESSIONS_MAX_MESSAGES": 400,
        "TOKEN_BUDGET": 120000,
        "COMPACTION_THRESHOLD_RATIO": 0.85,
        "NODE_ENABLED": True,
        "NODE_HOST": "0.0.0.0",
        "NODE_TOKENS": {},
        "SUBAGENT_WS_PORT": 9800,
        "GIT_USERNAME": "",
        "GIT_TOKEN": "",
        "WEBUI_ENABLED": True,
        "WEBUI_HOST": "0.0.0.0",
        "WEBUI_PORT": 8080,
        "WEBUI_TOKEN": "",
        "LOGGING": {
            "enabled": True,
            "level": "info",
            "dir": "logs",
            "segmentMaxMB": 64,
            "retentionDays": 14,
            "maxTotalGB": 5,
            "retentionCheckEvery": 200,
            "stream": {
                "queueSize": 2000,
            },
            "search": {
                "defaultLimit": 200,
                "maxLimit": 5000,
            },
        },
        "HEARTBEAT_ENABLED": True,
        "HEARTBEAT_INTERVAL_S": 1800,
        "MAX_GLOBAL_SUBAGENT_CONCURRENT": 10,
        "MAX_SESSION_SUBAGENT_CONCURRENT": 8,
    }


DEFAULTS = build_defaults()
PATH_KEYS = {"WORKSPACE_PATH", "SESSIONS_DIR", "VECTOR_DB_PATH"}
SENSITIVE_KEYS = {
    "DINGTALK_CLIENT_SECRET",
    "NAPCAT_ACCESS_TOKEN",
    "LLM_API_KEY",
    "EMBEDDING_API_KEY",
    "BRAVE_API_KEY",
    "GIT_TOKEN",
    "WEBUI_TOKEN",
}
